import type { Metadata } from "next";
import { Header } from "../components/dashboard/Header/Header";
import "./globals.css";

export const metadata: Metadata = {
    title: "Create Next App dashboard",
    description: "Generated by create next app",
};

export default function RLayout({
    children
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className="flex h-screen flex-col md:flex-row md:overflow-hidden">
                <div className="w-full flex-none md:w-64">
                    <Header />
                </div>
                <div className="flex-grow p-6 md:overflow-y-auto md:p-12">{children}</div>
            </body>
        </html>
    );
}
