import type { Metadata } from "next";
//import "./globals.css";

export const metadata: Metadata = {
    title: "Create Next App dashboard",
    description: "Generated by create next app",
};


export default function RLayout({
    children
}: Readonly<{
    children: React.ReactNode;
}>) {


    return (
        <html lang="en">
            <body className="bg-white">
                <p>text</p>
                {children}
            </body>
        </html>
    );
}
